version: "2"
linters:
  enable:
    - bodyclose
    - errorlint
    - misspell
    - revive
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - bin
      - dist
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - bin
      - dist
      - third_party$
      - builtin$
      - examples$
